version: "3.9"

services:
  server:
    image: python:3.11-slim
    working_dir: /app/server
    volumes:
      - ./server:/app/server
      - ./server/app/static_sender:/app/server/app/static_sender
      - ./server/app/static_dashboard:/app/server/app/static_dashboard
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
